### PR TITLE
Correcting names and stub steps...

### PR DESCRIPTION
**Pull request by gintominto5329**

### CODE REVIEW

**Comment by gitman-2021** [comment]
This was the 1st Pull/Merge request of my life.
So, please be a little soft...

**Review by purnavikas — APPROVED** [review]
Hh

**Comment by tytydraco** [comment]
> This was the 1st Pull/Merge request of my life. So, please be a little soft...

Sorry for doing this so late, I didn't notice. Merged!

**Comment by tytydraco** [comment]
If you can update this for the latest readme so there's no conflicts I'll merge it asap ❤️

**Pull request closed without merging**
